# Imagen base de Python
FROM python:3.11

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos necesarios
COPY requirements.txt .

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto que el bot usará
EXPOSE 25978
EXPOSE 26206

# Ejecutar el bot
CMD ["python", "src/main.py"]
