services:
  gatobot:
    build: 
      context: .
      dockerfile: Dockerfile
      no_cache: true
    image: gatobot:latest
    ports:
      - "25978:25978"
      - "26206:26206"
    env_file: ".env"