services:
  gatobot:
    image: python:3.11
    restart: always
    ports:
      - "25978:25978"
      - "26206:26206"
    env_file: ".env"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: [ "/app/entrypoint.sh" ]
